### PR TITLE
Feature/add key field to sign up page

### PR DESCRIPTION
**Pull request by WildCard-NO**
**Before:**
image

**After:**
image

In order to make a new account, you will need to fill the "Enter Key" Field.
The key for now is set to "Ruby"
If you where to write something other than Ruby, like "ruby" or "Table" you will get an error message:
image

This will make it harder for unnecessary people to get access to the site.
Feedback on how to make it more safe and secure from strangers are welcomed :lock:

### CODE REVIEW

**Comment by Jordybastien** [comment]
I've joined a bit late, I mean I'm not sure how secure we want to protect new users from signing up in the first phase but here's what I think or could suggest, please correct me if I'm wrong.

As far as I understand I think the first user creating an organization should always be able to register the same way as getharvest, but then for people to join their organization and be assigned to projects they would need to be invited this could be with a magic link/OTP etc.


If we do not need users to sign up in the first phase, I would then suggest implementing an invitation-only registration, We may not set up and create the emails/SMS for now but the rest of it, something like an expirable token or an expirable OTP to be used in this process

**Review by str1fe — APPROVED** [review]
Well done @WildCard-NO. Clean and tidy PR! :clap:

**Comment by str1fe** [comment]
I agree with you @Jordybastien. Using invitations is a better solution long term. However i think it's ok to start simple like this, for our MVP.

**Comment by Jordybastien** [comment]
> I agree with you @Jordybastien. Using invitations is a better solution long term. However i think it's ok to start simple like this, for our MVP.

Absolutely, I agree with you. I was not aware of the scope for MVP @str1fe

**Comment by str1fe** [comment]
No worries @Jordybastien . I'm really glad you give your opinion. Keep doing that!

**Pull request merged**
